// SPDX-License-Identifier: LicenseRef-PaperRune-Health-Sector-Restricted-1.0
// Copyright (c) 2026 cssBruno

package main

import (
	"fmt"
	"log"
	"strings"

	"github.com/cssbruno/paperrune/document"
	"github.com/cssbruno/paperrune/examples/internal/outpath"
)

func main() {
	pdf := document.MustNew()
	pdf.SetTitle("Day-to-day Service Report", false)
	pdf.SetCreator("examples/day-to-day-report", false)
	pdf.SetMargins(14, 28, 14)
	pdf.SetAutoPageBreak(true, 18)
	pdf.AliasNbPages("{total}")
	setHeaderFooter(pdf)

	pdf.AddPage()
	pdf.SetFont("Helvetica", "", 10)

	fragment := reportHTML()
	html := pdf.HTMLNew()
	html.AllowLocalImages = true
	if messages := html.ValidateHTML(fragment); len(messages) > 0 {
		log.Fatalf("unsupported HTML/CSS in example: %s", strings.Join(messages, "; "))
	}
	compiled, err := document.CompileHTML(fragment)
	if err != nil {
		log.Fatal(err)
	}
	html.WriteCompiled(5.3, compiled)

	if err := pdf.OutputFileAndClose(outpath.File("day-to-day-report.pdf")); err != nil {
		log.Fatal(err)
	}
}

func setHeaderFooter(pdf *document.Document) {
	pdf.SetHeaderFunc(func() {
		pdf.SetFillColor(31, 54, 82)
		pdf.Rect(0, 0, 210, 20, "F")
		pdf.SetTextColor(255, 255, 255)
		pdf.SetFont("Helvetica", "B", 10)
		pdf.SetXY(14, 7)
		pdf.CellFormat(90, 5, "Day-to-day service report", "", 0, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 8)
		pdf.SetXY(118, 7)
		pdf.CellFormat(78, 5, "Acme Logistics - June 30, 2026", "", 0, "R", false, 0, "")
		pdf.SetTextColor(0, 0, 0)
		pdf.SetY(28)
	})

	pdf.SetFooterFunc(func() {
		pdf.SetY(-14)
		pdf.SetDrawColor(205, 213, 222)
		pdf.Line(14, 281, 196, 281)
		pdf.SetFont("Helvetica", "", 8)
		pdf.SetTextColor(95, 105, 115)
		pdf.CellFormat(90, 7, "Generated by PaperRune", "", 0, "L", false, 0, "")
		pdf.CellFormat(0, 7, fmt.Sprintf("Page %d / {total}", pdf.PageNo()), "", 0, "R", false, 0, "")
		pdf.SetTextColor(0, 0, 0)
	})
}

func reportHTML() string {
	return `
		<style>
			h1 { color: #1f3652; font-size: 18pt; margin: 0 0 3mm 0; }
			h2 { color: #1f3652; font-size: 13pt; margin: 5mm 0 2mm 0; }
			h3 { color: #2b3c4f; font-size: 10pt; margin: 0 0 2mm 0; }
			p { color: #3f4b59; font-size: 9.5pt; line-height: 1.35; margin: 0 0 2.5mm 0; }
			.small { color: #687384; font-size: 8pt; }
			.note {
				background-color: #f3f8fc;
				border-left: 3px solid #2d7dd2;
				border-top: 1px solid #d8e4ef;
				border-right: 1px solid #d8e4ef;
				border-bottom: 1px solid #d8e4ef;
				border-top-right-radius: 3mm;
				border-bottom-right-radius: 3mm;
				padding: 3mm;
				margin: 3mm 0 4mm 0;
			}
			.warning {
				background-color: #fff8e7;
				border-left: 3px solid #d69222;
				border-top: 1px solid #ead8ad;
				border-right: 1px solid #ead8ad;
				border-bottom: 1px solid #ead8ad;
				padding: 3mm;
				margin: 3mm 0;
			}
			.identity {
				display: flex;
				gap: 3mm;
				align-items: stretch;
				margin: 2mm 0 4mm 0;
			}
			.identity-card {
				flex: 1;
				background-color: #f8fafc;
				border: 1px solid #c8d2df;
				border-radius: 2mm;
				padding: 3mm;
			}
			.metric-row {
				display: flex;
				gap: 3mm;
				align-items: stretch;
				margin: 2mm 0 4mm 0;
			}
			.metric-card {
				flex: 1;
				background-color: #eef6f1;
				border: 1px solid #b7d1bf;
				border-radius: 2mm;
				padding: 3mm;
			}
			table { width: 100%; border-collapse: collapse; margin: 2mm 0 4mm 0; }
			th {
				background-color: #e8eef5;
				color: #1f3652;
				border: 1px solid #aebcce;
				font-size: 8.5pt;
				font-weight: bold;
				padding: 2mm;
				text-align: left;
			}
			td {
				border: 1px solid #c8d2df;
				color: #394654;
				font-size: 8.5pt;
				padding: 2mm;
				vertical-align: top;
			}
			.metric-value { color: #166944; font-size: 16pt; font-weight: bold; }
			.right { text-align: right; }
			.center { text-align: center; }
			.total td { background-color: #f4f7fb; font-weight: bold; }
			.approval td { background-color: #fbfcfd; height: 14mm; }
		</style>

		<div class="identity">
			<div class="identity-card">Customer<br><strong>Acme Logistics</strong><br><span class="small">Regional operations team<br>ops@example.test</span></div>
			<div class="identity-card">Document<br><strong>Weekly service summary</strong><br><span class="small">Report ID: OPS-2026-0630<br>Prepared by: PDF Services</span></div>
			<div class="identity-card">SLA<br><strong><span class="metric-value">98.7%</span></strong><br><span class="small">On-time dispatch</span></div>
		</div>

		<h1>Weekly Operations Summary</h1>
		<p class="note">This is a practical two-page document: customer details, metrics, work completed, next actions, risks, schedule, and approval fields. It uses the supported PaperRune HTML/CSS subset with compiled HTML for repeat rendering.</p>

		<div class="metric-row">
			<div class="metric-card"><span class="metric-value">1,284</span><br><strong>Orders processed</strong><br><span class="small">Across 6 warehouses</span></div>
			<div class="metric-card"><span class="metric-value">42 min</span><br><strong>Median resolution</strong><br><span class="small">Support queue</span></div>
			<div class="metric-card"><span class="metric-value">$18.4k</span><br><strong>Open invoices</strong><br><span class="small">Due this week</span></div>
		</div>

		<h2>Completed Work</h2>
		<table>
			<thead>
				<tr><th width="16%">Ref</th><th width="39%">Task</th><th width="18%">Owner</th><th width="14%">Status</th><th width="13%" class="right">Hours</th></tr>
			</thead>
			<tbody>
				<tr><td>OPS-1042</td><td>Imported delivery exceptions from partner CSV files</td><td>Platform</td><td>Done</td><td class="right">4.0</td></tr>
				<tr><td>OPS-1043</td><td>Generated customer-facing invoice packet PDFs</td><td>Billing</td><td>Done</td><td class="right">2.5</td></tr>
				<tr><td>OPS-1044</td><td>Reviewed delayed shipments and sent carrier follow-ups</td><td>Support</td><td>Done</td><td class="right">3.0</td></tr>
				<tr><td>OPS-1045</td><td>Updated warehouse pick-list template and barcode labels</td><td>Fulfillment</td><td>Review</td><td class="right">1.5</td></tr>
				<tr><td>OPS-1046</td><td>Audited address normalization failures for enterprise accounts</td><td>Data</td><td>Done</td><td class="right">2.0</td></tr>
			</tbody>
			<tfoot>
				<tr class="total"><td colspan="4">Total tracked time</td><td class="right">13.0</td></tr>
			</tfoot>
		</table>

		<div style="page-break-before: always"></div>
		<h1>Next Actions and Approval</h1>
		<table>
			<thead>
				<tr><th width="44%">Next action</th><th width="20%">Due</th><th width="20%">Owner</th><th width="16%">Priority</th></tr>
			</thead>
			<tbody>
				<tr><td>Send revised invoice packet to customer finance team</td><td>Jul 01, 2026</td><td>Billing</td><td>High</td></tr>
				<tr><td>Confirm carrier exception codes for warehouse 3</td><td>Jul 02, 2026</td><td>Operations</td><td>Medium</td></tr>
				<tr><td>Publish updated pick-list PDF template</td><td>Jul 03, 2026</td><td>Fulfillment</td><td>Medium</td></tr>
				<tr><td>Review weekly scorecard with account owner</td><td>Jul 06, 2026</td><td>Account Team</td><td>Normal</td></tr>
			</tbody>
		</table>

		<p class="warning"><strong>Risk note: </strong>Warehouse 3 still has intermittent carrier status mismatches. Keep the daily reconciliation job enabled until the partner confirms their code mapping.</p>

		<h2>Schedule Snapshot</h2>
		<table>
			<thead>
				<tr><th width="22%">Day</th><th width="30%">Morning</th><th width="30%">Afternoon</th><th width="18%">Coverage</th></tr>
			</thead>
			<tbody>
				<tr><td>Monday</td><td>Import review</td><td>Invoice packet QA</td><td>Full</td></tr>
				<tr><td>Tuesday</td><td>Carrier follow-up</td><td>Dispatch audit</td><td>Full</td></tr>
				<tr><td>Wednesday</td><td>Template release</td><td>Customer review</td><td>Partial</td></tr>
				<tr><td>Thursday</td><td>Open-risk review</td><td>Account sync</td><td>Full</td></tr>
			</tbody>
		</table>

		<h2>Approval</h2>
		<table class="approval">
			<tr>
				<td width="50%"><strong>Prepared by</strong><br><br>PDF Services Team</td>
				<td width="50%"><strong>Approved by</strong><br><br></td>
			</tr>
		</table>
		<p class="small">Implementation note: the summary cards above use PaperRune's supported flexbox subset, and metric values use styled span elements.</p>
	`
}
