// SPDX-License-Identifier: LicenseRef-PaperRune-Health-Sector-Restricted-1.0
// Copyright (c) 2026 cssBruno

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"go/types"
	"os"
	"reflect"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/tools/go/packages"
)

type generator struct {
	pkg       *types.Package
	structs   map[string]*types.Named
	sequence  int
	usedBytes bool
	usedFloat bool
}

func main() {
	outputPath := flag.String("output", "", "generated Go output file")
	flag.Parse()
	if *outputPath == "" || flag.NArg() != 0 {
		panic("usage: canonical-json-gen -output FILE")
	}
	config := &packages.Config{Mode: packages.NeedName | packages.NeedTypes | packages.NeedImports | packages.NeedDeps, Dir: ".."}
	loaded, err := packages.Load(config, "github.com/cssbruno/paperrune/internal/layoutengine")
	if err != nil || len(loaded) != 1 || len(loaded[0].Errors) != 0 {
		if len(loaded) == 1 {
			panic(fmt.Sprintf("load layoutengine: %v %v", err, loaded[0].Errors))
		}
		panic(fmt.Sprintf("load layoutengine: %v (%d packages)", err, len(loaded)))
	}
	pkg := loaded[0].Types
	g := &generator{pkg: pkg, structs: map[string]*types.Named{}}
	for _, name := range []string{"CanonicalTreeProjection", "LayoutPlanProjection"} {
		object := pkg.Scope().Lookup(name)
		if object == nil {
			panic("missing root type " + name)
		}
		g.collect(object.Type())
	}

	var output bytes.Buffer
	output.WriteString("// SPDX-License-Identifier: LicenseRef-PaperRune-Health-Sector-Restricted-1.0\n")
	output.WriteString("// Copyright (c) 2026 cssBruno\n\n")
	output.WriteString("// Code generated by tools/canonical-json-gen; DO NOT EDIT.\n\n")
	output.WriteString("package layoutengine\n\n")
	names := make([]string, 0, len(g.structs))
	for name := range g.structs {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		g.emitNamedStruct(&output, g.structs[name])
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		_ = os.WriteFile(*outputPath+".broken", output.Bytes(), 0o644)
		panic(err)
	}
	if err := os.WriteFile(*outputPath, formatted, 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("generated %d struct encoders (bytes=%v floats=%v)\n", len(names), g.usedBytes, g.usedFloat)
}

func (g *generator) collect(value types.Type) {
	value = types.Unalias(value)
	switch typed := value.(type) {
	case *types.Named:
		if object := typed.Obj(); object.Pkg() == g.pkg {
			if _, ok := typed.Underlying().(*types.Struct); ok {
				if _, exists := g.structs[object.Name()]; exists {
					return
				}
				g.structs[object.Name()] = typed
			}
		}
		g.collect(typed.Underlying())
	case *types.Pointer:
		g.collect(typed.Elem())
	case *types.Slice:
		g.collect(typed.Elem())
	case *types.Array:
		g.collect(typed.Elem())
	case *types.Struct:
		for index := 0; index < typed.NumFields(); index++ {
			field := typed.Field(index)
			if field.Exported() {
				g.collect(field.Type())
			}
		}
	case *types.Basic:
		return
	default:
		panic(fmt.Sprintf("unsupported reachable type %T %s", value, value))
	}
}

func (g *generator) emitNamedStruct(output *bytes.Buffer, named *types.Named) {
	name := named.Obj().Name()
	fmt.Fprintf(output, "func encodeCanonical%s(encoder *canonicalHashEncoder, value %s) {\n", name, name)
	g.emitStruct(output, named.Underlying().(*types.Struct), "value", "\t")
	output.WriteString("}\n\n")
}

func (g *generator) emitStruct(output *bytes.Buffer, structure *types.Struct, expression, indent string) {
	fmt.Fprintf(output, "%sencoder.writeRaw(\"{\")\n", indent)
	fmt.Fprintf(output, "%sfirst := true\n", indent)
	for index := 0; index < structure.NumFields(); index++ {
		field := structure.Field(index)
		if !field.Exported() {
			continue
		}
		tag, options := jsonTag(structure.Tag(index), field.Name())
		if tag == "-" {
			continue
		}
		if field.Anonymous() && !strings.Contains(structure.Tag(index), `json:"`) {
			panic("anonymous untagged field is unsupported: " + field.String())
		}
		if options["string"] {
			panic("json string option is unsupported: " + field.String())
		}
		fieldExpression := expression + "." + field.Name()
		conditions := make([]string, 0, 2)
		if options["omitempty"] {
			conditions = append(conditions, "!("+emptyCondition(field.Type(), fieldExpression)+")")
		}
		if options["omitzero"] {
			conditions = append(conditions, "!("+g.zeroCondition(field.Type(), fieldExpression)+")")
		}
		fieldIndent := indent
		if len(conditions) != 0 {
			fmt.Fprintf(output, "%sif %s {\n", indent, strings.Join(conditions, " && "))
			fieldIndent += "\t"
		}
		literal := strconv.Quote("\"" + tag + "\":")
		fmt.Fprintf(output, "%sencoder.writeField(&first, %s)\n", fieldIndent, literal)
		g.emitValue(output, field.Type(), fieldExpression, fieldIndent)
		if len(conditions) != 0 {
			fmt.Fprintf(output, "%s}\n", indent)
		}
	}
	fmt.Fprintf(output, "%sencoder.writeRaw(\"}\")\n", indent)
}

func (g *generator) emitValue(output *bytes.Buffer, value types.Type, expression, indent string) {
	value = types.Unalias(value)
	if named, ok := value.(*types.Named); ok {
		if _, ok := named.Underlying().(*types.Struct); ok && named.Obj().Pkg() == g.pkg {
			fmt.Fprintf(output, "%sencodeCanonical%s(encoder, %s)\n", indent, named.Obj().Name(), expression)
			return
		}
		g.emitValue(output, named.Underlying(), expression, indent)
		return
	}
	switch typed := value.(type) {
	case *types.Basic:
		switch typed.Kind() {
		case types.Bool:
			fmt.Fprintf(output, "%sencoder.writeBool(%s)\n", indent, expression)
		case types.String:
			fmt.Fprintf(output, "%sencoder.writeString(string(%s))\n", indent, expression)
		case types.Int, types.Int8, types.Int16, types.Int32, types.Int64:
			fmt.Fprintf(output, "%sencoder.writeInt(int64(%s))\n", indent, expression)
		case types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64, types.Uintptr:
			fmt.Fprintf(output, "%sencoder.writeUint(uint64(%s))\n", indent, expression)
		case types.Float32:
			g.usedFloat = true
			fmt.Fprintf(output, "%sencoder.writeFloat(float64(%s), 32)\n", indent, expression)
		case types.Float64:
			g.usedFloat = true
			fmt.Fprintf(output, "%sencoder.writeFloat(float64(%s), 64)\n", indent, expression)
		default:
			panic("unsupported basic type: " + typed.String())
		}
	case *types.Pointer:
		fmt.Fprintf(output, "%sif %s == nil {\n", indent, expression)
		fmt.Fprintf(output, "%s\tencoder.writeRaw(\"null\")\n", indent)
		fmt.Fprintf(output, "%s} else {\n", indent)
		g.emitValue(output, typed.Elem(), "*"+parenthesize(expression), indent+"\t")
		fmt.Fprintf(output, "%s}\n", indent)
	case *types.Slice:
		if basic, ok := types.Unalias(typed.Elem()).Underlying().(*types.Basic); ok && basic.Kind() == types.Uint8 {
			g.usedBytes = true
			fmt.Fprintf(output, "%sencoder.writeBytes(%s)\n", indent, expression)
			return
		}
		sequence := g.nextSequence()
		fmt.Fprintf(output, "%sif %s == nil {\n", indent, expression)
		fmt.Fprintf(output, "%s\tencoder.writeRaw(\"null\")\n", indent)
		fmt.Fprintf(output, "%s} else {\n", indent)
		fmt.Fprintf(output, "%s\tencoder.writeRaw(\"[\")\n", indent)
		fmt.Fprintf(output, "%s\tfor index%d := range %s {\n", indent, sequence, expression)
		fmt.Fprintf(output, "%s\t\tif index%d != 0 { encoder.writeRaw(\",\") }\n", indent, sequence)
		g.emitValue(output, typed.Elem(), fmt.Sprintf("%s[index%d]", expression, sequence), indent+"\t\t")
		fmt.Fprintf(output, "%s\t}\n", indent)
		fmt.Fprintf(output, "%s\tencoder.writeRaw(\"]\")\n", indent)
		fmt.Fprintf(output, "%s}\n", indent)
	case *types.Array:
		sequence := g.nextSequence()
		fmt.Fprintf(output, "%sencoder.writeRaw(\"[\")\n", indent)
		fmt.Fprintf(output, "%sfor index%d := range %s {\n", indent, sequence, expression)
		fmt.Fprintf(output, "%s\tif index%d != 0 { encoder.writeRaw(\",\") }\n", indent, sequence)
		g.emitValue(output, typed.Elem(), fmt.Sprintf("%s[index%d]", expression, sequence), indent+"\t")
		fmt.Fprintf(output, "%s}\n", indent)
		fmt.Fprintf(output, "%sencoder.writeRaw(\"]\")\n", indent)
	case *types.Struct:
		g.emitStruct(output, typed, expression, indent)
	default:
		panic(fmt.Sprintf("unsupported encoded type %T %s", value, value))
	}
}

func (g *generator) nextSequence() int {
	g.sequence++
	return g.sequence
}

func (g *generator) zeroCondition(value types.Type, expression string) string {
	if !types.Comparable(value) {
		panic("non-comparable omitzero field: " + value.String())
	}
	return expression + " == (" + types.TypeString(value, func(pkg *types.Package) string {
		if pkg == g.pkg {
			return ""
		}
		return pkg.Name()
	}) + "{})"
}

func emptyCondition(value types.Type, expression string) string {
	underlying := types.Unalias(value).Underlying()
	switch typed := underlying.(type) {
	case *types.Basic:
		switch typed.Kind() {
		case types.Bool:
			return "!" + parenthesize(expression)
		case types.String:
			return "len(" + expression + ") == 0"
		case types.Int, types.Int8, types.Int16, types.Int32, types.Int64,
			types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64, types.Uintptr,
			types.Float32, types.Float64:
			return expression + " == 0"
		}
	case *types.Array:
		return fmt.Sprintf("len(%s) == 0", expression)
	case *types.Slice, *types.Map:
		return "len(" + expression + ") == 0"
	case *types.Pointer, *types.Interface:
		return expression + " == nil"
	case *types.Struct:
		return "false"
	}
	panic("unsupported omitempty type: " + value.String())
}

func jsonTag(raw, fallback string) (string, map[string]bool) {
	value, ok := reflect.StructTag(raw).Lookup("json")
	if !ok {
		return fallback, map[string]bool{}
	}
	parts := strings.Split(value, ",")
	name := parts[0]
	if name == "" {
		name = fallback
	}
	options := make(map[string]bool, len(parts)-1)
	for _, option := range parts[1:] {
		options[option] = true
	}
	return name, options
}

func parenthesize(expression string) string { return "(" + expression + ")" }
