// SPDX-License-Identifier: LicenseRef-PaperRune-Health-Sector-Restricted-1.0
// Copyright (c) 2026 cssBruno

package document

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/gob"
	"encoding/hex"
	"errors"
	"fmt"
	"hash"
	"io"
	"math"
	"strconv"
)

// ImageInfo stores parsed image data and PDF object metadata for a registered
// image.
type ImageInfo struct {
	data  []byte  // Raw image data
	smask []byte  // Soft mask, an 8-bit per-pixel transparency mask
	n     int     // Image object number
	w     float64 // Width
	h     float64 // Height
	cs    string  // Color space
	pal   []byte  // Image color palette
	bpc   int     // Bits Per Component
	f     string  // Image filter
	dp    string  // DecodeParms
	trns  []int   // Transparency mask
	scale float64 // Document scale factor
	dpi   float64 // dots per inch found from the image file (PNG only)
	i     string  // SHA-256 checksum of intrinsic image values
}

type imageResourceID [32]byte

func (info *ImageInfo) clone() *ImageInfo {
	if info == nil {
		return nil
	}
	clone := *info
	clone.data = append([]byte(nil), info.data...)
	clone.smask = append([]byte(nil), info.smask...)
	clone.pal = append([]byte(nil), info.pal...)
	clone.trns = append([]int(nil), info.trns...)
	clone.n = 0
	return &clone
}

func (info *ImageInfo) cloneMetadata() *ImageInfo {
	if info == nil {
		return nil
	}
	clone := *info
	clone.n = 0
	return &clone
}

func generateImageID(info *ImageInfo) (string, error) {
	id, err := generateImageResourceID(info)
	if err != nil {
		return "", err
	}
	return hex.EncodeToString(id[:]), nil
}

func generateImageResourceID(info *ImageInfo) (imageResourceID, error) {
	var id imageResourceID
	if info == nil {
		return id, errors.New("image info is nil")
	}
	h := sha256.New()
	hashImageBytes(h, 'd', info.data)
	hashImageBytes(h, 'm', info.smask)
	hashImageFloat(h, 'w', info.w)
	hashImageFloat(h, 'h', info.h)
	hashImageString(h, 'c', info.cs)
	hashImageBytes(h, 'p', info.pal)
	hashImageInt(h, 'b', info.bpc)
	hashImageString(h, 'f', info.f)
	hashImageString(h, 'q', info.dp)
	hashImageInt(h, 't', len(info.trns))
	for _, value := range info.trns {
		hashImageInt(h, 'v', value)
	}
	hashImageFloat(h, 'i', info.dpi)
	copy(id[:], h.Sum(nil))
	return id, nil
}

func hashImageBytes(h hash.Hash, tag byte, value []byte) {
	var scratch [9]byte
	scratch[0] = tag
	binary.BigEndian.PutUint64(scratch[1:], uint64(len(value)))
	h.Write(scratch[:])
	h.Write(value)
}

func hashImageString(h hash.Hash, tag byte, value string) {
	var scratch [9]byte
	scratch[0] = tag
	binary.BigEndian.PutUint64(scratch[1:], uint64(len(value)))
	h.Write(scratch[:])
	_, _ = io.WriteString(h, value)
}

func hashImageInt(h hash.Hash, tag byte, value int) {
	var scratch [9]byte
	scratch[0] = tag
	binary.BigEndian.PutUint64(scratch[1:], uint64(int64(value))) // #nosec G115 -- Stable image hashes deliberately preserve signed int bits.
	h.Write(scratch[:])
}

func hashImageFloat(h hash.Hash, tag byte, value float64) {
	var scratch [9]byte
	scratch[0] = tag
	binary.BigEndian.PutUint64(scratch[1:], math.Float64bits(value))
	h.Write(scratch[:])
}

// GobEncode encodes the receiving image to a byte slice.
func (info *ImageInfo) GobEncode() (buf []byte, err error) {
	fields := []any{info.data, info.smask, info.n, info.w, info.h, info.cs,
		info.pal, info.bpc, info.f, info.dp, info.trns, info.scale, info.dpi}
	w := new(bytes.Buffer)
	encoder := gob.NewEncoder(w)
	for j := 0; j < len(fields) && err == nil; j++ {
		err = encoder.Encode(fields[j])
	}
	if err == nil {
		buf = w.Bytes()
	}
	return
}

// GobDecode decodes the specified byte buffer (generated by GobEncode) into
// the receiving image.
func (info *ImageInfo) GobDecode(buf []byte) (err error) {
	fields := []any{&info.data, &info.smask, &info.n, &info.w, &info.h,
		&info.cs, &info.pal, &info.bpc, &info.f, &info.dp, &info.trns, &info.scale, &info.dpi}
	r := bytes.NewBuffer(buf)
	decoder := gob.NewDecoder(r)
	for j := 0; j < len(fields) && err == nil; j++ {
		err = decoder.Decode(fields[j])
	}

	info.i, err = generateImageID(info)
	return
}

func (info *ImageInfo) validForPDF() error {
	if info == nil {
		return errors.New("image info is nil")
	}
	if info.w <= 0 || info.h <= 0 || math.IsNaN(info.w) || math.IsNaN(info.h) || math.IsInf(info.w, 0) || math.IsInf(info.h, 0) {
		return errors.New("invalid image dimensions")
	}
	switch info.cs {
	case "DeviceGray", "DeviceRGB", "DeviceCMYK":
	case "Indexed":
		if len(info.pal) == 0 || len(info.pal)%3 != 0 {
			return errors.New("invalid indexed image palette")
		}
	default:
		return fmt.Errorf("invalid image color space: %s", info.cs)
	}
	if info.bpc <= 0 || info.bpc > 16 {
		return errors.New("invalid image bits per component")
	}
	switch info.f {
	case "", "FlateDecode", "DCTDecode":
	default:
		return fmt.Errorf("invalid image filter: %s", info.f)
	}
	if info.dp != "" && !validImageDecodeParams(info.dp) {
		return errors.New("invalid image decode parameters")
	}
	return nil
}

func validImageDecodeParams(params string) bool {
	names := [...]string{"/Predictor", "/Colors", "/BitsPerComponent", "/Columns"}
	var values [4]int
	for i, name := range names {
		var token string
		token, params = nextImageDecodeParamToken(params)
		if token != name {
			return false
		}
		token, params = nextImageDecodeParamToken(params)
		n, err := strconv.Atoi(token)
		if err != nil {
			return false
		}
		values[i] = n
	}
	if token, _ := nextImageDecodeParamToken(params); token != "" {
		return false
	}
	predictor, colors, bitsPerComponent, columns := values[0], values[1], values[2], values[3]
	if predictor < 1 || predictor > 15 {
		return false
	}
	if colors != 1 && colors != 3 && colors != 4 {
		return false
	}
	switch bitsPerComponent {
	case 1, 2, 4, 8, 16:
	default:
		return false
	}
	return columns > 0
}

func nextImageDecodeParamToken(s string) (string, string) {
	for len(s) > 0 {
		switch s[0] {
		case ' ', '\t', '\n', '\r', '\f':
			s = s[1:]
		default:
			goto token
		}
	}
	return "", ""
token:
	for i := 0; i < len(s); i++ {
		switch s[i] {
		case ' ', '\t', '\n', '\r', '\f':
			return s[:i], s[i+1:]
		}
	}
	return s, ""
}

// Extent returns the width and height of the image in the units of the Document
// object.
func (info *ImageInfo) Extent() (wd, ht float64) {
	return info.Width(), info.Height()
}

// Width returns the width of the image in the units of the Document object.
func (info *ImageInfo) Width() float64 {
	if info == nil {
		return 0
	}
	return info.w / (info.scale * info.dpi / 72)
}

// Height returns the height of the image in the units of the Document object.
func (info *ImageInfo) Height() float64 {
	if info == nil {
		return 0
	}
	return info.h / (info.scale * info.dpi / 72)
}

// SetDpi sets the dots per inch for an image. PNG images may have their DPI set
// automatically if the image specifies it. DPI information is not currently
// available automatically for JPEG, GIF, and WebP images, so callers can set it
// here when it matters. It defaults to 72 DPI.
func (info *ImageInfo) SetDpi(dpi float64) {
	if info == nil || !finiteNumbers(dpi) || dpi <= 0 {
		return
	}
	info.dpi = dpi
}
