// SPDX-License-Identifier: LicenseRef-PaperRune-Health-Sector-Restricted-1.0
// Copyright (c) 2026 cssBruno

package main

import (
	"fmt"
	"log"
	"strings"

	"github.com/cssbruno/paperrune/document"
	"github.com/cssbruno/paperrune/examples/internal/outpath"
)

func main() {
	pdf := document.MustNew()
	pdf.SetTitle("HTML Tables", false)
	pdf.SetCreator("examples/html-tables", false)
	pdf.SetMargins(16, 16, 16)
	pdf.AddPage()
	pdf.SetFont("Helvetica", "", 10)

	var rows strings.Builder
	for i := 1; i <= 34; i++ {
		status := "Ready"
		if i%4 == 0 {
			status = "Review"
		}
		_, _ = fmt.Fprintf(&rows, `<tr><td>INV-%04d</td><td>Document workflow %02d</td><td class="status">%s</td><td class="amount">$%d.00</td></tr>`, 4100+i, i, status, 125+i*17)
	}

	html := pdf.HTMLNew()
	html.Write(5.5, `
		<style>
			h1 { color: #1f2d3d; margin-bottom: 6px; }
			p { color: #3c4652; line-height: 1.35; }
			table {
				width: 100%;
				border-collapse: collapse;
				border: 1px solid #9aa8b5;
				margin-top: 6px;
			}
			caption {
				color: #49515c;
				font-size: 9pt;
				margin-bottom: 4px;
			}
			th {
				background-color: #e8eef5;
				color: #1f2d3d;
				border: 1px solid #9aa8b5;
				padding: 4px;
				text-align: left;
			}
			td {
				border: 1px solid #c6d0da;
				padding: 3px 4px;
			}
			td.status { color: #1f6f4a; }
			td.amount { text-align: right; }
			tfoot td {
				background-color: #f4f7fa;
				font-weight: bold;
			}
		</style>
		<h1>HTML Table Report</h1>
		<p>This example renders a generated HTML table with a caption, header, body rows, footer, borders, padding, alignment, and automatic page flow.</p>
		<table border="1" cellpadding="3" bordercolor="#c6d0da">
			<caption>Open billing jobs</caption>
			<thead>
				<tr><th>Reference</th><th>Description</th><th>Status</th><th>Amount</th></tr>
			</thead>
			<tbody>`+rows.String()+`</tbody>
			<tfoot>
				<tr><td colspan="3">Rows generated by Go before HTML rendering</td><td class="amount">34</td></tr>
			</tfoot>
		</table>
	`)

	if err := pdf.OutputFileAndClose(outpath.File("html-tables.pdf")); err != nil {
		log.Fatal(err)
	}
}
