// SPDX-License-Identifier: LicenseRef-PaperRune-Health-Sector-Restricted-1.0
// Copyright (c) 2026 cssBruno

// Code generated by tools/canonical-json-gen; DO NOT EDIT.

package layoutengine

func encodeCanonicalBreakDecision(encoder *canonicalHashEncoder, value BreakDecision) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"reason\":")
	encoder.writeString(string(value.Reason))
	encoder.writeField(&first, "\"from_page\":")
	encoder.writeUint(uint64(value.FromPage))
	encoder.writeField(&first, "\"to_page\":")
	encoder.writeUint(uint64(value.ToPage))
	encoder.writeField(&first, "\"region\":")
	encoder.writeString(string(value.Region))
	encoder.writeField(&first, "\"preceding_fragment\":")
	encoder.writeUint(uint64(value.Preceding))
	encoder.writeField(&first, "\"triggering_fragment\":")
	encoder.writeUint(uint64(value.Triggering))
	encoder.writeField(&first, "\"required_height\":")
	encoder.writeInt(int64(value.Required))
	encoder.writeField(&first, "\"available_height\":")
	encoder.writeInt(int64(value.Available))
	encoder.writeRaw("}")
}

func encodeCanonicalCanonicalTreeProjection(encoder *canonicalHashEncoder, value CanonicalTreeProjection) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"schema_version\":")
	encoder.writeUint(uint64(value.SchemaVersion))
	encoder.writeField(&first, "\"nodes\":")
	if value.Nodes == nil {
		encoder.writeRaw("null")
	} else {
		encoder.writeRaw("[")
		for index1 := range value.Nodes {
			if index1 != 0 {
				encoder.writeRaw(",")
			}
			encodeCanonicalTreeNode(encoder, value.Nodes[index1])
		}
		encoder.writeRaw("]")
	}
	if !(len(value.Children) == 0) {
		encoder.writeField(&first, "\"children\":")
		if value.Children == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index2 := range value.Children {
				if index2 != 0 {
					encoder.writeRaw(",")
				}
				encoder.writeUint(uint64(value.Children[index2]))
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Strings) == 0) {
		encoder.writeField(&first, "\"strings\":")
		if value.Strings == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index3 := range value.Strings {
				if index3 != 0 {
					encoder.writeRaw(",")
				}
				encoder.writeString(string(value.Strings[index3]))
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Styles) == 0) {
		encoder.writeField(&first, "\"styles\":")
		if value.Styles == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index4 := range value.Styles {
				if index4 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalTreeStyle(encoder, value.Styles[index4])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Tracks) == 0) {
		encoder.writeField(&first, "\"tracks\":")
		if value.Tracks == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index5 := range value.Tracks {
				if index5 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalTreeTrack(encoder, value.Tracks[index5])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Resources) == 0) {
		encoder.writeField(&first, "\"resources\":")
		if value.Resources == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index6 := range value.Resources {
				if index6 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalTreeResource(encoder, value.Resources[index6])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Semantics) == 0) {
		encoder.writeField(&first, "\"semantics\":")
		if value.Semantics == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index7 := range value.Semantics {
				if index7 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalTreeSemantic(encoder, value.Semantics[index7])
			}
			encoder.writeRaw("]")
		}
	}
	encoder.writeRaw("}")
}

func encodeCanonicalContentAddressedResource(encoder *canonicalHashEncoder, value ContentAddressedResource) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"kind\":")
	encoder.writeString(string(value.Kind))
	encoder.writeField(&first, "\"name\":")
	encoder.writeString(string(value.Name))
	encoder.writeField(&first, "\"digest\":")
	encoder.writeString(string(value.Digest))
	encoder.writeRaw("}")
}

func encodeCanonicalCoreFontResource(encoder *canonicalHashEncoder, value CoreFontResource) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"id\":")
	encoder.writeUint(uint64(value.ID))
	if !(len(value.Face) == 0) {
		encoder.writeField(&first, "\"face\":")
		encoder.writeString(string(value.Face))
	}
	encoder.writeField(&first, "\"metrics_digest\":")
	encoder.writeString(string(value.MetricsDigest))
	if !(value.EmbeddedUTF8 == nil) {
		encoder.writeField(&first, "\"embedded_utf8\":")
		if value.EmbeddedUTF8 == nil {
			encoder.writeRaw("null")
		} else {
			encodeCanonicalEmbeddedUTF8Font(encoder, *(value.EmbeddedUTF8))
		}
	}
	encoder.writeRaw("}")
}

func encodeCanonicalCoreGlyphRun(encoder *canonicalHashEncoder, value CoreGlyphRun) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"line\":")
	encoder.writeUint(uint64(value.Line))
	encoder.writeField(&first, "\"font\":")
	encoder.writeUint(uint64(value.Font))
	encoder.writeField(&first, "\"font_size\":")
	encoder.writeInt(int64(value.FontSize))
	encoder.writeField(&first, "\"color\":")
	encodeCanonicalCoreRGBColor(encoder, value.Color)
	if !(value.Opacity == 0) {
		encoder.writeField(&first, "\"opacity\":")
		encoder.writeInt(int64(value.Opacity))
	}
	encoder.writeField(&first, "\"origin\":")
	encodeCanonicalPoint(encoder, value.Origin)
	encoder.writeField(&first, "\"codes\":")
	encoder.writeString(string(value.Codes))
	if !(!(value.LeadingSpace)) {
		encoder.writeField(&first, "\"leading_space\":")
		encoder.writeBool(value.LeadingSpace)
	}
	if !(!(value.TrailingSpace)) {
		encoder.writeField(&first, "\"trailing_space\":")
		encoder.writeBool(value.TrailingSpace)
	}
	encoder.writeField(&first, "\"advances\":")
	if value.Advances == nil {
		encoder.writeRaw("null")
	} else {
		encoder.writeRaw("[")
		for index8 := range value.Advances {
			if index8 != 0 {
				encoder.writeRaw(",")
			}
			encoder.writeInt(int64(value.Advances[index8]))
		}
		encoder.writeRaw("]")
	}
	encoder.writeField(&first, "\"source\":")
	encodeCanonicalSourceSpan(encoder, value.Source)
	encoder.writeRaw("}")
}

func encodeCanonicalCoreRGBColor(encoder *canonicalHashEncoder, value CoreRGBColor) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"r\":")
	encoder.writeUint(uint64(value.R))
	encoder.writeField(&first, "\"g\":")
	encoder.writeUint(uint64(value.G))
	encoder.writeField(&first, "\"b\":")
	encoder.writeUint(uint64(value.B))
	encoder.writeField(&first, "\"set\":")
	encoder.writeBool(value.Set)
	encoder.writeRaw("}")
}

func encodeCanonicalDeterministicInputManifest(encoder *canonicalHashEncoder, value DeterministicInputManifest) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"plan_id\":")
	encoder.writeString(string(value.PlanID))
	encoder.writeField(&first, "\"semantic_template_id\":")
	encoder.writeString(string(value.SemanticTemplateID))
	encoder.writeField(&first, "\"scenario_revision_id\":")
	encoder.writeString(string(value.ScenarioRevisionID))
	encoder.writeField(&first, "\"resource_catalog\":")
	encodeCanonicalResourceCatalogManifest(encoder, value.ResourceCatalog)
	encoder.writeField(&first, "\"locale\":")
	encoder.writeString(string(value.Locale))
	encoder.writeField(&first, "\"timezone\":")
	encoder.writeString(string(value.Timezone))
	encoder.writeField(&first, "\"text_data\":")
	encodeCanonicalTextDataVersions(encoder, value.TextData)
	encoder.writeField(&first, "\"compatibility_profile\":")
	encoder.writeString(string(value.CompatibilityProfile))
	if !(len(value.CompatibilityFlags) == 0) {
		encoder.writeField(&first, "\"compatibility_flags\":")
		if value.CompatibilityFlags == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index9 := range value.CompatibilityFlags {
				if index9 != 0 {
					encoder.writeRaw(",")
				}
				encoder.writeString(string(value.CompatibilityFlags[index9]))
			}
			encoder.writeRaw("]")
		}
	}
	encoder.writeField(&first, "\"page_profile\":")
	encodeCanonicalPageProfileManifest(encoder, value.PageProfile)
	encoder.writeField(&first, "\"planner_version\":")
	encoder.writeString(string(value.PlannerVersion))
	encoder.writeRaw("}")
}

func encodeCanonicalDiagnostic(encoder *canonicalHashEncoder, value Diagnostic) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"code\":")
	encoder.writeString(string(value.Code))
	encoder.writeField(&first, "\"severity\":")
	encoder.writeString(string(value.Severity))
	encoder.writeField(&first, "\"stage\":")
	encoder.writeString(string(value.Stage))
	encoder.writeField(&first, "\"message\":")
	encoder.writeString(string(value.Message))
	encoder.writeField(&first, "\"location\":")
	encodeCanonicalDiagnosticLocation(encoder, value.Location)
	if !(len(value.Evidence) == 0) {
		encoder.writeField(&first, "\"evidence\":")
		if value.Evidence == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index10 := range value.Evidence {
				if index10 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalDiagnosticEvidence(encoder, value.Evidence[index10])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Related) == 0) {
		encoder.writeField(&first, "\"related\":")
		if value.Related == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index11 := range value.Related {
				if index11 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalDiagnosticReference(encoder, value.Related[index11])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Fixes) == 0) {
		encoder.writeField(&first, "\"fixes\":")
		if value.Fixes == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index12 := range value.Fixes {
				if index12 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalDiagnosticFix(encoder, value.Fixes[index12])
			}
			encoder.writeRaw("]")
		}
	}
	encoder.writeRaw("}")
}

func encodeCanonicalDiagnosticEvidence(encoder *canonicalHashEncoder, value DiagnosticEvidence) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"key\":")
	encoder.writeString(string(value.Key))
	encoder.writeField(&first, "\"value\":")
	encoder.writeString(string(value.Value))
	encoder.writeRaw("}")
}

func encodeCanonicalDiagnosticFix(encoder *canonicalHashEncoder, value DiagnosticFix) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"kind\":")
	encoder.writeString(string(value.Kind))
	encoder.writeField(&first, "\"target\":")
	encoder.writeString(string(value.Target))
	if !(len(value.Property) == 0) {
		encoder.writeField(&first, "\"property\":")
		encoder.writeString(string(value.Property))
	}
	if !(len(value.Value) == 0) {
		encoder.writeField(&first, "\"value\":")
		encoder.writeString(string(value.Value))
	}
	encoder.writeRaw("}")
}

func encodeCanonicalDiagnosticLocation(encoder *canonicalHashEncoder, value DiagnosticLocation) {
	encoder.writeRaw("{")
	first := true
	if !(value.Node == 0) {
		encoder.writeField(&first, "\"node\":")
		encoder.writeUint(uint64(value.Node))
	}
	if !(len(value.Key) == 0) {
		encoder.writeField(&first, "\"key\":")
		encoder.writeString(string(value.Key))
	}
	encoder.writeField(&first, "\"source\":")
	encodeCanonicalSourceSpan(encoder, value.Source)
	if !(len(value.Instance) == 0) {
		encoder.writeField(&first, "\"instance\":")
		encoder.writeString(string(value.Instance))
	}
	if !(value.Fragment == 0) {
		encoder.writeField(&first, "\"fragment\":")
		encoder.writeUint(uint64(value.Fragment))
	}
	if !(len(value.Scenario) == 0) {
		encoder.writeField(&first, "\"scenario\":")
		encoder.writeString(string(value.Scenario))
	}
	if !(value.Page == 0) {
		encoder.writeField(&first, "\"page\":")
		encoder.writeUint(uint64(value.Page))
	}
	if !(len(value.Region) == 0) {
		encoder.writeField(&first, "\"region\":")
		encoder.writeString(string(value.Region))
	}
	encoder.writeField(&first, "\"bounds\":")
	encodeCanonicalRect(encoder, value.Bounds)
	if !(!(value.HasBounds)) {
		encoder.writeField(&first, "\"has_bounds\":")
		encoder.writeBool(value.HasBounds)
	}
	encoder.writeRaw("}")
}

func encodeCanonicalDiagnosticReference(encoder *canonicalHashEncoder, value DiagnosticReference) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"code\":")
	encoder.writeString(string(value.Code))
	encoder.writeField(&first, "\"location\":")
	encodeCanonicalDiagnosticLocation(encoder, value.Location)
	encoder.writeRaw("}")
}

func encodeCanonicalDisplayCommand(encoder *canonicalHashEncoder, value DisplayCommand) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"kind\":")
	encoder.writeString(string(value.Kind))
	if !(value.Fragment == 0) {
		encoder.writeField(&first, "\"fragment\":")
		encoder.writeUint(uint64(value.Fragment))
	}
	encoder.writeField(&first, "\"bounds\":")
	encodeCanonicalRect(encoder, value.Bounds)
	encoder.writeField(&first, "\"payload\":")
	encoder.writeUint(uint64(value.Payload))
	encoder.writeRaw("}")
}

func encodeCanonicalEmbeddedUTF8Font(encoder *canonicalHashEncoder, value EmbeddedUTF8Font) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"name\":")
	encoder.writeString(string(value.Name))
	encoder.writeField(&first, "\"digest\":")
	encoder.writeString(string(value.Digest))
	encoder.writeField(&first, "\"byte_length\":")
	encoder.writeUint(uint64(value.ByteLength))
	encoder.writeRaw("}")
}

func encodeCanonicalFragment(encoder *canonicalHashEncoder, value Fragment) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"id\":")
	encoder.writeUint(uint64(value.ID))
	encoder.writeField(&first, "\"node\":")
	encoder.writeUint(uint64(value.Node))
	encoder.writeField(&first, "\"key\":")
	encoder.writeString(string(value.Key))
	encoder.writeField(&first, "\"instance\":")
	encoder.writeString(string(value.Instance))
	encoder.writeField(&first, "\"page\":")
	encoder.writeUint(uint64(value.Page))
	encoder.writeField(&first, "\"region\":")
	encoder.writeString(string(value.Region))
	encoder.writeField(&first, "\"margin_box\":")
	encodeCanonicalRect(encoder, value.MarginBox)
	encoder.writeField(&first, "\"border_box\":")
	encodeCanonicalRect(encoder, value.BorderBox)
	encoder.writeField(&first, "\"padding_box\":")
	encodeCanonicalRect(encoder, value.PaddingBox)
	encoder.writeField(&first, "\"content_box\":")
	encodeCanonicalRect(encoder, value.ContentBox)
	encoder.writeField(&first, "\"source\":")
	encodeCanonicalSourceSpan(encoder, value.Source)
	encoder.writeField(&first, "\"continuation\":")
	encoder.writeString(string(value.Continuation))
	if !(!(value.Repeated)) {
		encoder.writeField(&first, "\"repeated\":")
		encoder.writeBool(value.Repeated)
	}
	encoder.writeRaw("}")
}

func encodeCanonicalImageCrop(encoder *canonicalHashEncoder, value ImageCrop) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"intrinsic\":")
	encodeCanonicalSize(encoder, value.Intrinsic)
	encoder.writeField(&first, "\"source\":")
	encodeCanonicalRect(encoder, value.Source)
	encoder.writeField(&first, "\"clip\":")
	encodeCanonicalRect(encoder, value.Clip)
	encoder.writeRaw("}")
}

func encodeCanonicalImageResource(encoder *canonicalHashEncoder, value ImageResource) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"id\":")
	encoder.writeUint(uint64(value.ID))
	encoder.writeField(&first, "\"digest\":")
	encoder.writeString(string(value.Digest))
	encoder.writeField(&first, "\"format\":")
	encoder.writeString(string(value.Format))
	encoder.writeField(&first, "\"pixel_width\":")
	encoder.writeUint(uint64(value.PixelWidth))
	encoder.writeField(&first, "\"pixel_height\":")
	encoder.writeUint(uint64(value.PixelHeight))
	encoder.writeRaw("}")
}

func encodeCanonicalIndexRange(encoder *canonicalHashEncoder, value IndexRange) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"start\":")
	encoder.writeUint(uint64(value.Start))
	encoder.writeField(&first, "\"count\":")
	encoder.writeUint(uint64(value.Count))
	encoder.writeRaw("}")
}

func encodeCanonicalLayoutPlanProjection(encoder *canonicalHashEncoder, value LayoutPlanProjection) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"schema_version\":")
	encoder.writeUint(uint64(value.SchemaVersion))
	encoder.writeField(&first, "\"planner_version\":")
	encoder.writeString(string(value.PlannerVersion))
	encoder.writeField(&first, "\"painter_contract_version\":")
	encoder.writeString(string(value.PainterContractVersion))
	if !(value.DeterministicInputs == nil) {
		encoder.writeField(&first, "\"deterministic_inputs\":")
		if value.DeterministicInputs == nil {
			encoder.writeRaw("null")
		} else {
			encodeCanonicalDeterministicInputManifest(encoder, *(value.DeterministicInputs))
		}
	}
	if !(len(value.Pages) == 0) {
		encoder.writeField(&first, "\"pages\":")
		if value.Pages == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index13 := range value.Pages {
				if index13 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalPlannedPage(encoder, value.Pages[index13])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Fragments) == 0) {
		encoder.writeField(&first, "\"fragments\":")
		if value.Fragments == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index14 := range value.Fragments {
				if index14 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalFragment(encoder, value.Fragments[index14])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Lines) == 0) {
		encoder.writeField(&first, "\"lines\":")
		if value.Lines == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index15 := range value.Lines {
				if index15 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalPlannedLine(encoder, value.Lines[index15])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.PageRegions) == 0) {
		encoder.writeField(&first, "\"page_regions\":")
		if value.PageRegions == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index16 := range value.PageRegions {
				if index16 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalPlannedPageRegion(encoder, value.PageRegions[index16])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.GridTracks) == 0) {
		encoder.writeField(&first, "\"grid_tracks\":")
		if value.GridTracks == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index17 := range value.GridTracks {
				if index17 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalPlannedGridTrack(encoder, value.GridTracks[index17])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Fonts) == 0) {
		encoder.writeField(&first, "\"fonts\":")
		if value.Fonts == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index18 := range value.Fonts {
				if index18 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalCoreFontResource(encoder, value.Fonts[index18])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.GlyphRuns) == 0) {
		encoder.writeField(&first, "\"glyph_runs\":")
		if value.GlyphRuns == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index19 := range value.GlyphRuns {
				if index19 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalCoreGlyphRun(encoder, value.GlyphRuns[index19])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.ImageResources) == 0) {
		encoder.writeField(&first, "\"image_resources\":")
		if value.ImageResources == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index20 := range value.ImageResources {
				if index20 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalImageResource(encoder, value.ImageResources[index20])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Images) == 0) {
		encoder.writeField(&first, "\"images\":")
		if value.Images == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index21 := range value.Images {
				if index21 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalPlannedImage(encoder, value.Images[index21])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Destinations) == 0) {
		encoder.writeField(&first, "\"destinations\":")
		if value.Destinations == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index22 := range value.Destinations {
				if index22 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalPlannedDestination(encoder, value.Destinations[index22])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Links) == 0) {
		encoder.writeField(&first, "\"links\":")
		if value.Links == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index23 := range value.Links {
				if index23 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalPlannedLink(encoder, value.Links[index23])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Paths) == 0) {
		encoder.writeField(&first, "\"paths\":")
		if value.Paths == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index24 := range value.Paths {
				if index24 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalPlannedPath(encoder, value.Paths[index24])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Transforms) == 0) {
		encoder.writeField(&first, "\"transforms\":")
		if value.Transforms == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index25 := range value.Transforms {
				if index25 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalTransform(encoder, value.Transforms[index25])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Clips) == 0) {
		encoder.writeField(&first, "\"clips\":")
		if value.Clips == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index26 := range value.Clips {
				if index26 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalPlannedClip(encoder, value.Clips[index26])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Fills) == 0) {
		encoder.writeField(&first, "\"fills\":")
		if value.Fills == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index27 := range value.Fills {
				if index27 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalPlannedFill(encoder, value.Fills[index27])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Strokes) == 0) {
		encoder.writeField(&first, "\"strokes\":")
		if value.Strokes == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index28 := range value.Strokes {
				if index28 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalPlannedStroke(encoder, value.Strokes[index28])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Commands) == 0) {
		encoder.writeField(&first, "\"commands\":")
		if value.Commands == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index29 := range value.Commands {
				if index29 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalDisplayCommand(encoder, value.Commands[index29])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Breaks) == 0) {
		encoder.writeField(&first, "\"breaks\":")
		if value.Breaks == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index30 := range value.Breaks {
				if index30 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalBreakDecision(encoder, value.Breaks[index30])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Diagnostics) == 0) {
		encoder.writeField(&first, "\"diagnostics\":")
		if value.Diagnostics == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index31 := range value.Diagnostics {
				if index31 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalDiagnostic(encoder, value.Diagnostics[index31])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.SemanticNodes) == 0) {
		encoder.writeField(&first, "\"semantic_nodes\":")
		if value.SemanticNodes == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index32 := range value.SemanticNodes {
				if index32 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalSemanticNode(encoder, value.SemanticNodes[index32])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.SemanticFragments) == 0) {
		encoder.writeField(&first, "\"semantic_fragments\":")
		if value.SemanticFragments == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index33 := range value.SemanticFragments {
				if index33 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalSemanticFragmentAssociation(encoder, value.SemanticFragments[index33])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.ReadingOrder) == 0) {
		encoder.writeField(&first, "\"reading_order\":")
		if value.ReadingOrder == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index34 := range value.ReadingOrder {
				if index34 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalReadingOccurrence(encoder, value.ReadingOrder[index34])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.Provenance) == 0) {
		encoder.writeField(&first, "\"provenance\":")
		if value.Provenance == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index35 := range value.Provenance {
				if index35 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalProvenanceEntry(encoder, value.Provenance[index35])
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.FragmentProvenance) == 0) {
		encoder.writeField(&first, "\"fragment_provenance\":")
		if value.FragmentProvenance == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index36 := range value.FragmentProvenance {
				if index36 != 0 {
					encoder.writeRaw(",")
				}
				encoder.writeUint(uint64(value.FragmentProvenance[index36]))
			}
			encoder.writeRaw("]")
		}
	}
	if !(len(value.LineProvenance) == 0) {
		encoder.writeField(&first, "\"line_provenance\":")
		if value.LineProvenance == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index37 := range value.LineProvenance {
				if index37 != 0 {
					encoder.writeRaw(",")
				}
				encoder.writeUint(uint64(value.LineProvenance[index37]))
			}
			encoder.writeRaw("]")
		}
	}
	encoder.writeRaw("}")
}

func encodeCanonicalPageProfileManifest(encoder *canonicalHashEncoder, value PageProfileManifest) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"id\":")
	encoder.writeString(string(value.ID))
	encoder.writeField(&first, "\"name\":")
	encoder.writeString(string(value.Name))
	encoder.writeField(&first, "\"width\":")
	encoder.writeInt(int64(value.Width))
	encoder.writeField(&first, "\"height\":")
	encoder.writeInt(int64(value.Height))
	encoder.writeRaw("}")
}

func encodeCanonicalPathSegment(encoder *canonicalHashEncoder, value PathSegment) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"kind\":")
	encoder.writeString(string(value.Kind))
	encoder.writeField(&first, "\"point\":")
	encodeCanonicalPoint(encoder, value.Point)
	encoder.writeField(&first, "\"control_1\":")
	encodeCanonicalPoint(encoder, value.Control1)
	encoder.writeField(&first, "\"control_2\":")
	encodeCanonicalPoint(encoder, value.Control2)
	encoder.writeRaw("}")
}

func encodeCanonicalPlannedClip(encoder *canonicalHashEncoder, value PlannedClip) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"path\":")
	encoder.writeUint(uint64(value.Path))
	encoder.writeField(&first, "\"rule\":")
	encoder.writeString(string(value.Rule))
	if !(value.Fragment == 0) {
		encoder.writeField(&first, "\"fragment\":")
		encoder.writeUint(uint64(value.Fragment))
	}
	encoder.writeRaw("}")
}

func encodeCanonicalPlannedDestination(encoder *canonicalHashEncoder, value PlannedDestination) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"id\":")
	encoder.writeUint(uint64(value.ID))
	encoder.writeField(&first, "\"page\":")
	encoder.writeUint(uint64(value.Page))
	if !(value.Fragment == 0) {
		encoder.writeField(&first, "\"fragment\":")
		encoder.writeUint(uint64(value.Fragment))
	}
	encoder.writeField(&first, "\"point\":")
	encodeCanonicalPoint(encoder, value.Point)
	encoder.writeField(&first, "\"source\":")
	encodeCanonicalSourceSpan(encoder, value.Source)
	encoder.writeRaw("}")
}

func encodeCanonicalPlannedFill(encoder *canonicalHashEncoder, value PlannedFill) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"path\":")
	encoder.writeUint(uint64(value.Path))
	encoder.writeField(&first, "\"rule\":")
	encoder.writeString(string(value.Rule))
	encoder.writeField(&first, "\"color\":")
	encodeCanonicalCoreRGBColor(encoder, value.Color)
	if !(value.Opacity == 0) {
		encoder.writeField(&first, "\"opacity\":")
		encoder.writeInt(int64(value.Opacity))
	}
	if !(value.Fragment == 0) {
		encoder.writeField(&first, "\"fragment\":")
		encoder.writeUint(uint64(value.Fragment))
	}
	encoder.writeRaw("}")
}

func encodeCanonicalPlannedGridTrack(encoder *canonicalHashEncoder, value PlannedGridTrack) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"group\":")
	encoder.writeUint(uint64(value.Group))
	encoder.writeField(&first, "\"page\":")
	encoder.writeUint(uint64(value.Page))
	encoder.writeField(&first, "\"region\":")
	encoder.writeString(string(value.Region))
	encoder.writeField(&first, "\"axis\":")
	encoder.writeString(string(value.Axis))
	encoder.writeField(&first, "\"index\":")
	encoder.writeUint(uint64(value.Index))
	encoder.writeField(&first, "\"bounds\":")
	encodeCanonicalRect(encoder, value.Bounds)
	if !(value.GapAfter == 0) {
		encoder.writeField(&first, "\"gap_after\":")
		encoder.writeInt(int64(value.GapAfter))
	}
	encoder.writeRaw("}")
}

func encodeCanonicalPlannedImage(encoder *canonicalHashEncoder, value PlannedImage) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"resource\":")
	encoder.writeUint(uint64(value.Resource))
	encoder.writeField(&first, "\"fragment\":")
	encoder.writeUint(uint64(value.Fragment))
	encoder.writeField(&first, "\"bounds\":")
	encodeCanonicalRect(encoder, value.Bounds)
	if !(value.Opacity == 0) {
		encoder.writeField(&first, "\"opacity\":")
		encoder.writeInt(int64(value.Opacity))
	}
	if !(value.Crop == nil) {
		encoder.writeField(&first, "\"crop\":")
		if value.Crop == nil {
			encoder.writeRaw("null")
		} else {
			encodeCanonicalImageCrop(encoder, *(value.Crop))
		}
	}
	encoder.writeField(&first, "\"source\":")
	encodeCanonicalSourceSpan(encoder, value.Source)
	encoder.writeRaw("}")
}

func encodeCanonicalPlannedLine(encoder *canonicalHashEncoder, value PlannedLine) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"fragment\":")
	encoder.writeUint(uint64(value.Fragment))
	encoder.writeField(&first, "\"index\":")
	encoder.writeUint(uint64(value.Index))
	encoder.writeField(&first, "\"bounds\":")
	encodeCanonicalRect(encoder, value.Bounds)
	encoder.writeField(&first, "\"baseline\":")
	encoder.writeInt(int64(value.Baseline))
	encoder.writeField(&first, "\"source\":")
	encodeCanonicalSourceSpan(encoder, value.Source)
	encoder.writeRaw("}")
}

func encodeCanonicalPlannedLink(encoder *canonicalHashEncoder, value PlannedLink) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"fragment\":")
	encoder.writeUint(uint64(value.Fragment))
	encoder.writeField(&first, "\"bounds\":")
	encodeCanonicalRect(encoder, value.Bounds)
	if !(value.Destination == 0) {
		encoder.writeField(&first, "\"destination\":")
		encoder.writeUint(uint64(value.Destination))
	}
	if !(len(value.URI) == 0) {
		encoder.writeField(&first, "\"uri\":")
		encoder.writeString(string(value.URI))
	}
	encoder.writeField(&first, "\"source\":")
	encodeCanonicalSourceSpan(encoder, value.Source)
	encoder.writeRaw("}")
}

func encodeCanonicalPlannedPage(encoder *canonicalHashEncoder, value PlannedPage) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"number\":")
	encoder.writeUint(uint64(value.Number))
	encoder.writeField(&first, "\"size\":")
	encodeCanonicalSize(encoder, value.Size)
	encoder.writeField(&first, "\"fragments\":")
	encodeCanonicalIndexRange(encoder, value.Fragments)
	encoder.writeField(&first, "\"lines\":")
	encodeCanonicalIndexRange(encoder, value.Lines)
	encoder.writeField(&first, "\"commands\":")
	encodeCanonicalIndexRange(encoder, value.Commands)
	encoder.writeRaw("}")
}

func encodeCanonicalPlannedPageRegion(encoder *canonicalHashEncoder, value PlannedPageRegion) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"page\":")
	encoder.writeUint(uint64(value.Page))
	encoder.writeField(&first, "\"region\":")
	encoder.writeString(string(value.Region))
	encoder.writeField(&first, "\"bounds\":")
	encodeCanonicalRect(encoder, value.Bounds)
	if !(len(value.Master) == 0) {
		encoder.writeField(&first, "\"master\":")
		encoder.writeString(string(value.Master))
	}
	encoder.writeRaw("}")
}

func encodeCanonicalPlannedPath(encoder *canonicalHashEncoder, value PlannedPath) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"segments\":")
	if value.Segments == nil {
		encoder.writeRaw("null")
	} else {
		encoder.writeRaw("[")
		for index38 := range value.Segments {
			if index38 != 0 {
				encoder.writeRaw(",")
			}
			encodeCanonicalPathSegment(encoder, value.Segments[index38])
		}
		encoder.writeRaw("]")
	}
	encoder.writeField(&first, "\"bounds\":")
	encodeCanonicalRect(encoder, value.Bounds)
	encoder.writeRaw("}")
}

func encodeCanonicalPlannedStroke(encoder *canonicalHashEncoder, value PlannedStroke) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"path\":")
	encoder.writeUint(uint64(value.Path))
	encoder.writeField(&first, "\"color\":")
	encodeCanonicalCoreRGBColor(encoder, value.Color)
	encoder.writeField(&first, "\"width\":")
	encoder.writeInt(int64(value.Width))
	if !(len(value.LineCap) == 0) {
		encoder.writeField(&first, "\"line_cap\":")
		encoder.writeString(string(value.LineCap))
	}
	if !(len(value.LineJoin) == 0) {
		encoder.writeField(&first, "\"line_join\":")
		encoder.writeString(string(value.LineJoin))
	}
	if !(len(value.Dash) == 0) {
		encoder.writeField(&first, "\"dash\":")
		if value.Dash == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index39 := range value.Dash {
				if index39 != 0 {
					encoder.writeRaw(",")
				}
				encoder.writeInt(int64(value.Dash[index39]))
			}
			encoder.writeRaw("]")
		}
	}
	if !(value.DashOffset == 0) {
		encoder.writeField(&first, "\"dash_offset\":")
		encoder.writeInt(int64(value.DashOffset))
	}
	if !(value.Opacity == 0) {
		encoder.writeField(&first, "\"opacity\":")
		encoder.writeInt(int64(value.Opacity))
	}
	if !(value.Fragment == 0) {
		encoder.writeField(&first, "\"fragment\":")
		encoder.writeUint(uint64(value.Fragment))
	}
	encoder.writeRaw("}")
}

func encodeCanonicalPoint(encoder *canonicalHashEncoder, value Point) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"x\":")
	encoder.writeInt(int64(value.X))
	encoder.writeField(&first, "\"y\":")
	encoder.writeInt(int64(value.Y))
	encoder.writeRaw("}")
}

func encodeCanonicalProvenanceEntry(encoder *canonicalHashEncoder, value ProvenanceEntry) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"node\":")
	encoder.writeUint(uint64(value.Node))
	encoder.writeField(&first, "\"key\":")
	encoder.writeString(string(value.Key))
	encoder.writeField(&first, "\"instance\":")
	encoder.writeString(string(value.Instance))
	encoder.writeField(&first, "\"source\":")
	encodeCanonicalSourceSpan(encoder, value.Source)
	encoder.writeRaw("}")
}

func encodeCanonicalReadingOccurrence(encoder *canonicalHashEncoder, value ReadingOccurrence) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"semantic\":")
	encoder.writeUint(uint64(value.Semantic))
	encoder.writeField(&first, "\"page\":")
	encoder.writeUint(uint64(value.Page))
	encoder.writeField(&first, "\"fragment\":")
	encoder.writeUint(uint64(value.Fragment))
	encoder.writeField(&first, "\"reading_index\":")
	encoder.writeUint(uint64(value.ReadingIndex))
	encoder.writeRaw("}")
}

func encodeCanonicalRect(encoder *canonicalHashEncoder, value Rect) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"x\":")
	encoder.writeInt(int64(value.X))
	encoder.writeField(&first, "\"y\":")
	encoder.writeInt(int64(value.Y))
	encoder.writeField(&first, "\"width\":")
	encoder.writeInt(int64(value.Width))
	encoder.writeField(&first, "\"height\":")
	encoder.writeInt(int64(value.Height))
	encoder.writeRaw("}")
}

func encodeCanonicalResourceCatalogManifest(encoder *canonicalHashEncoder, value ResourceCatalogManifest) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"id\":")
	encoder.writeString(string(value.ID))
	if !(len(value.Resources) == 0) {
		encoder.writeField(&first, "\"resources\":")
		if value.Resources == nil {
			encoder.writeRaw("null")
		} else {
			encoder.writeRaw("[")
			for index40 := range value.Resources {
				if index40 != 0 {
					encoder.writeRaw(",")
				}
				encodeCanonicalContentAddressedResource(encoder, value.Resources[index40])
			}
			encoder.writeRaw("]")
		}
	}
	encoder.writeRaw("}")
}

func encodeCanonicalSemanticAttributes(encoder *canonicalHashEncoder, value SemanticAttributes) {
	encoder.writeRaw("{")
	first := true
	if !(len(value.Language) == 0) {
		encoder.writeField(&first, "\"language\":")
		encoder.writeString(string(value.Language))
	}
	if !(len(value.AlternateText) == 0) {
		encoder.writeField(&first, "\"alternate_text\":")
		encoder.writeString(string(value.AlternateText))
	}
	if !(len(value.ActualText) == 0) {
		encoder.writeField(&first, "\"actual_text\":")
		encoder.writeString(string(value.ActualText))
	}
	if !(value.HeadingLevel == 0) {
		encoder.writeField(&first, "\"heading_level\":")
		encoder.writeUint(uint64(value.HeadingLevel))
	}
	if !(value.LinkDestination == 0) {
		encoder.writeField(&first, "\"link_destination\":")
		encoder.writeUint(uint64(value.LinkDestination))
	}
	if !(!(value.TableHeader)) {
		encoder.writeField(&first, "\"table_header\":")
		encoder.writeBool(value.TableHeader)
	}
	if !(len(value.TableScope) == 0) {
		encoder.writeField(&first, "\"table_scope\":")
		encoder.writeString(string(value.TableScope))
	}
	if !(value.TableRowSpan == 0) {
		encoder.writeField(&first, "\"table_row_span\":")
		encoder.writeUint(uint64(value.TableRowSpan))
	}
	if !(value.TableColumnSpan == 0) {
		encoder.writeField(&first, "\"table_column_span\":")
		encoder.writeUint(uint64(value.TableColumnSpan))
	}
	if !(len(value.FormLabel) == 0) {
		encoder.writeField(&first, "\"form_label\":")
		encoder.writeString(string(value.FormLabel))
	}
	if !(value.KeyboardOrder == 0) {
		encoder.writeField(&first, "\"keyboard_order\":")
		encoder.writeUint(uint64(value.KeyboardOrder))
	}
	encoder.writeRaw("}")
}

func encodeCanonicalSemanticFragmentAssociation(encoder *canonicalHashEncoder, value SemanticFragmentAssociation) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"semantic\":")
	encoder.writeUint(uint64(value.Semantic))
	encoder.writeField(&first, "\"page\":")
	encoder.writeUint(uint64(value.Page))
	encoder.writeField(&first, "\"fragment\":")
	encoder.writeUint(uint64(value.Fragment))
	encoder.writeRaw("}")
}

func encodeCanonicalSemanticNode(encoder *canonicalHashEncoder, value SemanticNode) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"id\":")
	encoder.writeUint(uint64(value.ID))
	if !(value.Parent == 0) {
		encoder.writeField(&first, "\"parent\":")
		encoder.writeUint(uint64(value.Parent))
	}
	encoder.writeField(&first, "\"role\":")
	encoder.writeString(string(value.Role))
	encoder.writeField(&first, "\"key\":")
	encoder.writeString(string(value.Key))
	encoder.writeField(&first, "\"instance\":")
	encoder.writeString(string(value.Instance))
	encoder.writeField(&first, "\"source\":")
	encodeCanonicalSourceSpan(encoder, value.Source)
	if !(value.Attributes == (SemanticAttributes{})) {
		encoder.writeField(&first, "\"attributes\":")
		encodeCanonicalSemanticAttributes(encoder, value.Attributes)
	}
	encoder.writeRaw("}")
}

func encodeCanonicalSize(encoder *canonicalHashEncoder, value Size) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"width\":")
	encoder.writeInt(int64(value.Width))
	encoder.writeField(&first, "\"height\":")
	encoder.writeInt(int64(value.Height))
	encoder.writeRaw("}")
}

func encodeCanonicalSourcePosition(encoder *canonicalHashEncoder, value SourcePosition) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"offset\":")
	encoder.writeUint(uint64(value.Offset))
	encoder.writeField(&first, "\"line\":")
	encoder.writeUint(uint64(value.Line))
	encoder.writeField(&first, "\"column\":")
	encoder.writeUint(uint64(value.Column))
	encoder.writeRaw("}")
}

func encodeCanonicalSourceSpan(encoder *canonicalHashEncoder, value SourceSpan) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"file\":")
	encoder.writeString(string(value.File))
	encoder.writeField(&first, "\"start\":")
	encodeCanonicalSourcePosition(encoder, value.Start)
	encoder.writeField(&first, "\"end\":")
	encodeCanonicalSourcePosition(encoder, value.End)
	encoder.writeRaw("}")
}

func encodeCanonicalTextDataVersions(encoder *canonicalHashEncoder, value TextDataVersions) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"unicode\":")
	encoder.writeString(string(value.Unicode))
	encoder.writeField(&first, "\"cldr\":")
	encoder.writeString(string(value.CLDR))
	encoder.writeField(&first, "\"hyphenation\":")
	encoder.writeString(string(value.Hyphenation))
	encoder.writeRaw("}")
}

func encodeCanonicalTransform(encoder *canonicalHashEncoder, value Transform) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"a\":")
	encoder.writeInt(int64(value.A))
	encoder.writeField(&first, "\"b\":")
	encoder.writeInt(int64(value.B))
	encoder.writeField(&first, "\"c\":")
	encoder.writeInt(int64(value.C))
	encoder.writeField(&first, "\"d\":")
	encoder.writeInt(int64(value.D))
	encoder.writeField(&first, "\"tx\":")
	encoder.writeInt(int64(value.TX))
	encoder.writeField(&first, "\"ty\":")
	encoder.writeInt(int64(value.TY))
	encoder.writeRaw("}")
}

func encodeCanonicalTreeLength(encoder *canonicalHashEncoder, value TreeLength) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"kind\":")
	encoder.writeString(string(value.Kind))
	if !(value.Value == 0) {
		encoder.writeField(&first, "\"value\":")
		encoder.writeInt(int64(value.Value))
	}
	encoder.writeRaw("}")
}

func encodeCanonicalTreeNode(encoder *canonicalHashEncoder, value TreeNode) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"id\":")
	encoder.writeUint(uint64(value.ID))
	encoder.writeField(&first, "\"key\":")
	encoder.writeString(string(value.Key))
	encoder.writeField(&first, "\"kind\":")
	encoder.writeUint(uint64(value.Kind))
	if !(value.Style == 0) {
		encoder.writeField(&first, "\"style\":")
		encoder.writeUint(uint64(value.Style))
	}
	if !(value.Track == 0) {
		encoder.writeField(&first, "\"track\":")
		encoder.writeUint(uint64(value.Track))
	}
	if !(value.Resource == 0) {
		encoder.writeField(&first, "\"resource\":")
		encoder.writeUint(uint64(value.Resource))
	}
	if !(value.Semantic == 0) {
		encoder.writeField(&first, "\"semantic\":")
		encoder.writeUint(uint64(value.Semantic))
	}
	if !(value.Text == 0) {
		encoder.writeField(&first, "\"text\":")
		encoder.writeUint(uint64(value.Text))
	}
	encoder.writeField(&first, "\"child_start\":")
	encoder.writeUint(uint64(value.ChildStart))
	encoder.writeField(&first, "\"child_count\":")
	encoder.writeUint(uint64(value.ChildCount))
	encoder.writeField(&first, "\"source\":")
	encodeCanonicalSourceSpan(encoder, value.Source)
	if !(value.Flags == 0) {
		encoder.writeField(&first, "\"flags\":")
		encoder.writeUint(uint64(value.Flags))
	}
	encoder.writeRaw("}")
}

func encodeCanonicalTreeResource(encoder *canonicalHashEncoder, value TreeResource) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"kind\":")
	encoder.writeUint(uint64(value.Kind))
	encoder.writeField(&first, "\"key\":")
	encoder.writeUint(uint64(value.Key))
	encoder.writeField(&first, "\"digest\":")
	encoder.writeUint(uint64(value.Digest))
	encoder.writeRaw("}")
}

func encodeCanonicalTreeSemantic(encoder *canonicalHashEncoder, value TreeSemantic) {
	encoder.writeRaw("{")
	first := true
	encoder.writeField(&first, "\"role\":")
	encoder.writeString(string(value.Role))
	if !(value.Label == 0) {
		encoder.writeField(&first, "\"label\":")
		encoder.writeUint(uint64(value.Label))
	}
	encoder.writeRaw("}")
}

func encodeCanonicalTreeStyle(encoder *canonicalHashEncoder, value TreeStyle) {
	encoder.writeRaw("{")
	first := true
	if !(value.FontFamily == 0) {
		encoder.writeField(&first, "\"font_family\":")
		encoder.writeUint(uint64(value.FontFamily))
	}
	if !(value.Align == 0) {
		encoder.writeField(&first, "\"align\":")
		encoder.writeUint(uint64(value.Align))
	}
	if !(value.FontSize == 0) {
		encoder.writeField(&first, "\"font_size\":")
		encoder.writeInt(int64(value.FontSize))
	}
	if !(value.LineHeight == 0) {
		encoder.writeField(&first, "\"line_height\":")
		encoder.writeInt(int64(value.LineHeight))
	}
	encoder.writeField(&first, "\"margin\":")
	encoder.writeRaw("[")
	for index41 := range value.Margin {
		if index41 != 0 {
			encoder.writeRaw(",")
		}
		encodeCanonicalTreeLength(encoder, value.Margin[index41])
	}
	encoder.writeRaw("]")
	if !(value.Flags == 0) {
		encoder.writeField(&first, "\"flags\":")
		encoder.writeUint(uint64(value.Flags))
	}
	encoder.writeRaw("}")
}

func encodeCanonicalTreeTrack(encoder *canonicalHashEncoder, value TreeTrack) {
	encoder.writeRaw("{")
	first := true
	if !(value.Name == 0) {
		encoder.writeField(&first, "\"name\":")
		encoder.writeUint(uint64(value.Name))
	}
	encoder.writeField(&first, "\"min\":")
	encodeCanonicalTreeLength(encoder, value.Min)
	encoder.writeField(&first, "\"max\":")
	encodeCanonicalTreeLength(encoder, value.Max)
	encoder.writeRaw("}")
}
